# Use an official Java runtime as a parent image
FROM openjdk:19

# Set the working directory in the container
WORKDIR /SIT

# Copy the current directory contents into the container at /app
COPY target/CICD_Project-v1.0.jar /SIT/

# run the application
CMD ["java", "-Denvironment=SIT", "-jar","/SIT/CICD_Project-v1.0.jar"]