# Use an official Java runtime as a parent image
FROM openjdk:19

# Set the working directory in the container
WORKDIR /DevVer

# Copy the current directory contents into the container at /app
COPY target/CICD_Project-v1.0.jar /DevVer/

# run the application
CMD ["java", "-Denvironment=DevVer", "-jar","/DevVer/CICD_Project-v1.0.jar"]