# Use an official Java runtime as a parent image
FROM openjdk:19

# Set the working directory in the container
WORKDIR /DevInt

# Copy the current directory contents into the container at /app
COPY target/CICD_Project-v1.0.jar /DevInt/

# run the application
CMD ["java", "-Denvironment=DevInt", "-jar","/DevInt/CICD_Project-v1.0.jar"]