name: Build & Test in DevVer and SIT

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  DevVer:
    runs-on: [self-hosted]
    strategy:
      matrix:
        browser: [ chrome ]
        profile: [ Localtests ]
        environment: [ DevVer ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache JDK
        id: cache-java
        uses: actions/cache@v4
        with:
          path: ~/action-runner/_work/_tool/Java_Temurin-Hotspot_jdk/19.0.2-7/x64
          key: ${{ runner.os }}-java-19-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-java-

#DEBUG
      - name: Debug Cache
        run: |
          echo "Cache hit: ${{ steps.cache-java.outputs.cache-hit }}"
          ls -la ~/action-runner/_work/_tool/Java_Temurin-Hotspot_jdk/19.0.2-7/x64

      - name: Verify Java version
        run: java -version

      - name: Check JAVA_HOME
        run: echo $JAVA_HOME
#DEBUG

      - name: Set up JDK 19
        if: steps.cache-java.outputs.cache-hit != 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'zulu'

      - name: Verify Java version
        run: java -version
      - name: Print JAVA_HOME
        run: echo $JAVA_HOME

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & Test DevVer with Maven
        run: mvn -B package --file pom.xml -Denvironment=${{matrix.environment}} -Dbrowser=${{ matrix.browser }} -P ${{ matrix.profile}}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: DevVer test results ${{ matrix.browser }} - ${{ github.run_id }}
          path: target/surefire-reports/

  DevInt:
    runs-on: [self-hosted]
    needs: DevVer
    strategy:
      matrix:
        browser: [ chrome, firefox ]
        profile: [ Localtests ]
        environment: [ DevInt ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache JDK
        id: cache-java
        uses: actions/cache@v4
        with:
          path: ~/action-runner/_work/_tool/Java_Temurin-Hotspot_jdk/19.0.2-7/x64
          key: ${{ runner.os }}-java-19-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-java-

      - name: Set up JDK 19
        if: steps.cache-java.outputs.cache-hit != 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          install-path: ~/action-runner/_work/_tool/Java_Temurin-Hotspot_jdk/19.0.2-7/x64

      - name: Verify Java version
        run: java -version
      - name: Print JAVA_HOME
        run: echo $JAVA_HOME

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & Test DevInt with Maven
        run: mvn -B package --file pom.xml -Denvironment=${{matrix.environment}} -Dbrowser=${{ matrix.browser }}  -P ${{ matrix.profile}}
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: DevInt test results ${{ matrix.browser }} - ${{ github.run_id }}
          path: target/surefire-reports/

  SIT:
    runs-on: [self-hosted]
    needs: DevInt
    strategy:
      matrix:
        profile: [ Browserstack ]
        environment: [ SIT ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache JDK
        id: cache-java
        uses: actions/cache@v4
        with:
          path: ~/action-runner/_work/_tool/Java_Temurin-Hotspot_jdk/19.0.2-7/x64
          key: ${{ runner.os }}-java-19-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-java-

      - name: Set up JDK 19
        if: steps.cache-java.outputs.cache-hit != 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          install-path: ~/action-runner/_work/_tool/Java_Temurin-Hotspot_jdk/19.0.2-7/x64

      - name: Verify Java version
        run: java -version
      - name: Print JAVA_HOME
        run: echo $JAVA_HOME

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & test SIT with Maven
        run: mvn -B package --file pom.xml -D environment=${{matrix.environment}} -P ${{ matrix.profile}}

#      - name: Remove remove previous Docker DevInt container instance
#        run: docker rm -f SIT
#      - name: Build Docker image
#        run: docker build . --file Dockerfile_SIT --tag cicd_project_image:SIT
#      - name: Run docker image
#        run: docker run --name SIT cicd_project_image:SIT

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: SIT test results ${{ matrix.browser }} - ${{ github.run_id }}
          path: target/surefire-reports/

  Production:
    runs-on: [self-hosted]
    needs: SIT
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'
